baseurl                  = "https://penguinone.kuropen.org"           # Your domain name
languageCode             = "ja-jp"
defaultContentLanguage   = "ja"
isMultilingual           = false
hasCJKLanguage           = true
title                    = "Penguinone"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "2006/01/02"
    dateformfull         = "2006/01/02 15:04"
    favicon              = "penguin.png"
    homepage             = "main"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "(C) Kuropen. Licensed under <a rel='license' href='https://creativecommons.org/licenses/by-nc-sa/4.0/'>CC-BY-NC-SA 4.0</a> unless otherwise noted."

# Metadata for Open Graph and Twitter
    description          = "Kuropen's Personal Website"          # Max 160 characters show in search results
    images               = ["penguin.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Penguinone"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/namegawa_shrine.mp4"
    type    = "video/mp4"
    poster  = "/namegawa_shrine.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "about"
    text = "where is this"

[[params.mainMenu]]
    link = "profile"
    text = "who I am"
 
[[params.mainMenu]]
    link = "posts"
    text = "my note"

[[params.mainMenu]]
    link = "gallery"
    text = "my picture"

[imaging]
    quality = 75

[markup.goldmark.renderer]
    unsafe = true
