---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/activitypub
  label: Activitypub
  create: all
  match: "**/*"
- type: directory
  path: content/polaris
  label: Polaris
  create: all
  match: "**/*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - sam-posts-frontmatter
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: content/posts/images
public_path: "/posts/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
version: 0.81.0
