name: Generate and Upload OGP Image
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Test if there is wrong slug"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install
      
      - name: Generating image
        run: yarn image-gen

      - name: Upload image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-1 build s3://penguinone-ogp-image/ --acl public-read
