name: Site Update
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install
      
      - name: Generating OGP image
        run: yarn image-gen

      - name: Upload OGP image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-1 og-image/out s3://ogp-img.kuropen.org/ --acl public-read

      - name: Building site
        run: yarn build

      - name: Uploading site
        run: yarn deploy
